export const MAINTENANCE_STATUS = {
  PENDING: "pending",
  APPROVED: "approved",
  SCHEDULED: "scheduled",
  DISAPPROVED: "disapproved",
  DONE: "done",
  CANCELLED: "cancelled",
};

export const MAINTENANCE_STATUS_ID = {
  PENDING: 1,
  APPROVED: 2,
  DISAPPROVED: 3,
  DONE: 4,
  CANCELLED: 5,
  COMPLETED: 8,
  SCHEDULED: 9,
};

const RAW_STATUS_ALIASES = {
  pending: MAINTENANCE_STATUS.PENDING,
  approved: MAINTENANCE_STATUS.APPROVED,
  confirmed: MAINTENANCE_STATUS.APPROVED,
  in_progress: MAINTENANCE_STATUS.APPROVED,
  scheduled: MAINTENANCE_STATUS.SCHEDULED,
  disapproved: MAINTENANCE_STATUS.DISAPPROVED,
  denied: MAINTENANCE_STATUS.DISAPPROVED,
  rejected: MAINTENANCE_STATUS.DISAPPROVED,
  done: MAINTENANCE_STATUS.DONE,
  completed: MAINTENANCE_STATUS.DONE,
  cancelled: MAINTENANCE_STATUS.CANCELLED,
  canceled: MAINTENANCE_STATUS.CANCELLED,
};

const STATUS_BY_ID = {
  [MAINTENANCE_STATUS_ID.PENDING]: MAINTENANCE_STATUS.PENDING,
  [MAINTENANCE_STATUS_ID.APPROVED]: MAINTENANCE_STATUS.APPROVED,
  [MAINTENANCE_STATUS_ID.COMPLETED]: MAINTENANCE_STATUS.DONE,
  [MAINTENANCE_STATUS_ID.SCHEDULED]: MAINTENANCE_STATUS.SCHEDULED,
  [MAINTENANCE_STATUS_ID.DISAPPROVED]: MAINTENANCE_STATUS.DISAPPROVED,
  [MAINTENANCE_STATUS_ID.DONE]: MAINTENANCE_STATUS.DONE,
  [MAINTENANCE_STATUS_ID.CANCELLED]: MAINTENANCE_STATUS.CANCELLED,
};

export function normalizeMaintenanceStatus(value, statusId) {
  const raw = String(value || "").trim().toLowerCase();
  if (raw && RAW_STATUS_ALIASES[raw]) return RAW_STATUS_ALIASES[raw];

  const n = Number(statusId);
  if (Number.isFinite(n) && STATUS_BY_ID[n]) return STATUS_BY_ID[n];

  return MAINTENANCE_STATUS.PENDING;
}

export default {};
